insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (1, 'CHUQUISACA', 'DEPTO', 'CHUQ', 1, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (53, 'LA PAZ', 'DEPTO', 'LAP', 2, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (181, 'COCHABAMBA', 'DEPTO', 'CBB', 3, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (263, 'ORURO', 'DEPTO', 'ORU', 4, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (333, 'POTOSI', 'DEPTO', 'PTS', 5, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (408, 'TARIJA', 'DEPTO', 'TAR', 6, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (434, 'SANTA CRUZ', 'DEPTO', 'SCZ', 7, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (523, 'BENI', 'DEPTO', 'BEN', 8, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (561, 'PANDO', 'DEPTO', 'PAN', 9, null);

insert into UBICACIONES_GEOGRAFICAS (ID_UBIGEO, DESC_UBIGEO, NIVEL, SIGLA_UBIGEO, UBIGEO, ID_PADRE)
values (589, 'NACIONAL', 'DEPTO', 'NAL', 10, null);
COMMIT;
